# Generated by Django 3.0.5 on 2020-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Adı')),
                ('price', models.CharField(max_length=300, verbose_name='Adı')),
            ],
        ),
    ]
